services:
  api:
    build:
      context: ./backend

  proxy:
    build:
      context: ./frontend
      args:
        DOMAIN: sudojo.io
        DEVELOPMENT: false

  tunnel:
    image: cloudflare/cloudflared:1710-3f6b1f24d036
    command: tunnel run --token ${TUNNEL_TOKEN}
