name: Client

on:
  push:
    tags: ["v*"]
    branches: ["main"]
    paths:
      - "client/**"
      - ".github/workflows/client.yaml"
  pull_request:
    branches: ["main"]
    paths:
      - "client/**"
      - ".github/workflows/client.yaml"

jobs:
  lint:
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 3
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: ./client/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: npx prettier --check .

  build:
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 10
    needs: lint
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6

      - name: Build image
        run: |
          docker build -t proxy:local --build-arg API_ENDPOINT=localhost:8080/api --build-arg INSECURE=true .

  publish:
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 10
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6

      - name: Build image
        run: |
          docker build -t proxy --build-arg API_ENDPOINT=sudojo.io/api .

      - name: Get tag name
        id: tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Tag and push
        run: |
          docker tag proxy ghcr.io/creed-braton/sudojo-proxy:${{ steps.tag.outputs.VERSION }}
          docker push ghcr.io/creed-braton/sudojo-proxy:${{ steps.tag.outputs.VERSION }}
